# Generated by Django 3.2.9 on 2022-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_mpio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_mpio', models.CharField(max_length=25)),
                ('subregion', models.CharField(max_length=20)),
                ('vocacion', models.CharField(max_length=20)),
            ],
        ),
    ]
