# Generated by Django 3.2.9 on 2022-03-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMpio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=50, verbose_name='Nombre Representante Legal')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=32)),
                ('telefono', models.CharField(max_length=11)),
                ('correo', models.CharField(max_length=32)),
                ('tipo_empresa', models.CharField(choices=[('GRANDE', 'GRANDE'), ('MEDIANA', 'MEDIANA'), ('PEQUEÑA', 'PEQUEÑA'), ('MICRO', 'MICRO')], default='GRANDE', max_length=7, verbose_name='Su Empresa es:')),
                ('cedula_representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMpio.representante')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMpio.municipio')),
            ],
        ),
    ]
