# Generated by Django 3.2.9 on 2022-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMpio', '0002_empresa_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cedula_representante',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cedula',
            field=models.CharField(default=11111, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_rep',
            field=models.CharField(default=11, max_length=50, verbose_name='Nombre Representante Legal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
