# Generated by Django 3.2.9 on 2022-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMpio', '0003_auto_20220308_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='vocacion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='camara',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciiu',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_dga',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_dga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_reg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_regdga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel_estudio',
            field=models.CharField(choices=[('TECNICO', 'TECNICO'), ('TECNOLOGO', 'TECNOLOGO'), ('PROFESIONAL', 'PROFESIONAL')], default='PROFESIONAL', max_length=32),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_dga',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector_prod',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titulo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_rep',
            field=models.CharField(max_length=64, verbose_name='Nombre Representante Legal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
