# Generated by Django 3.2.9 on 2022-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMpio', '0004_auto_20220405_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_dga',
            field=models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO'), ('APOYO GREMIO', 'APOYO GREMIO')], default='INTERNO', max_length=12, verbose_name='Tipo Departamento Gestion Ambiental'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_dga',
            field=models.CharField(max_length=64),
        ),
    ]
